"""
GARMENT SEGMENTATION, MEASURED RATHER THAN EYEBALLED.

Every other test in this project asks "did the code run?". These ask
"was the answer any good?", which for a cut-out means one number:
intersection-over-union against the garment's true shape.

The images are composites, not phone photographs, and that is the
whole point - the garment outline is known to the pixel, so a mask can
be scored instead of admired. Each case reproduces a condition a real
upload has to survive: a tiled floor, a wooden floor, a bedsheet with
folds, a patterned throw, a white shirt on white bedding, a black
shirt on a dark floor, dim light, and phone-camera blur. They are
generated by backend/tests/segmentation_bench/make_bench.py, which also
has a scorer for comparing engines by hand.

WHAT THE NUMBERS WERE, on the 14-case benchmark:

    before this suite existed    mean IoU 0.896, worst case 0.003
      (OpenCV GrabCut alone)     - a white t-shirt on a white bed came
                                   out as a scrap of bedsheet, and was
                                   STORED, because nothing checked
    after, no rembg installed    mean IoU 0.949, worst case 0.724
    after, with rembg installed  mean IoU 0.970, worst case 0.831

The thresholds below are set for the no-rembg case, because that is
what a fresh clone has. They are floors, not targets: if a change drops
the mean below 0.90 or lets any single case fall under 0.55, something
has regressed and this suite says so instead of a user discovering it.
"""
import os
import sys
import unittest

try:
    import numpy as np
    import cv2  # noqa: F401
    from PIL import Image
    HAVE_DEPS = True
except ImportError:
    HAVE_DEPS = False

BENCH_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         "segmentation_bench")

MEAN_IOU_FLOOR = 0.90
WORST_CASE_FLOOR = 0.55
# Cases nobody should be able to break without noticing: a garment on a
# floor or a bed is the ordinary upload this app exists for.
EVERYDAY_CASES = {
    "tshirt_tiled_floor": 0.90,
    "tshirt_on_bed": 0.90,
    "tshirt_wooden_floor": 0.90,
    "jeans_tiled_floor": 0.90,
    "dress_floral_bed": 0.90,
}


def _iou(pred, truth):
    p, t = pred > 0.5, truth > 0.5
    union = (p | t).sum()
    return float((p & t).sum() / union) if union else 0.0


@unittest.skipUnless(HAVE_DEPS, "numpy/opencv/Pillow not installed here")
class SegmentationQualityTests(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        sys.path.insert(0, BENCH_DIR)
        from backend import image_pipeline
        cls.pipeline = image_pipeline

        # Built on demand rather than committed: 28 PNGs of synthetic
        # fabric are not worth putting in git, and generating them is
        # deterministic (the generator seeds its own RNG).
        if not os.path.isdir(os.path.join(BENCH_DIR, "bench")):
            import make_bench
            cwd = os.getcwd()
            os.chdir(BENCH_DIR)
            try:
                make_bench.build()
            finally:
                os.chdir(cwd)

        cls.cases = sorted(
            name[:-4] for name in os.listdir(os.path.join(BENCH_DIR, "bench"))
            if name.endswith(".png") and not name.endswith("_truth.png")
            and name != "contact_sheet.png"
        )

        cls.scores = {}
        cls.engines = {}
        cls.kept = set()

        for case in cls.cases:
            img = Image.open(os.path.join(BENCH_DIR, "bench", f"{case}.png")).convert("RGB")
            truth = np.asarray(
                Image.open(os.path.join(BENCH_DIR, "bench", f"{case}_truth.png"))
            ).astype(np.float32) / 255.0
            mask, engine = image_pipeline.segment(img)
            cls.engines[case] = engine
            if mask is None:
                cls.scores[case] = 0.0
                cls.kept.add(case)
                continue
            cls.scores[case] = _iou(mask, truth)

    def test_the_benchmark_covers_the_conditions_people_actually_photograph(self):
        for expected in ("tshirt_tiled_floor", "tshirt_on_bed",
                         "white_tshirt_white_bed", "black_tshirt_dark_floor",
                         "tshirt_patterned_throw", "tshirt_phone_blur",
                         "tshirt_dim_light", "jeans_tiled_floor",
                         "dress_floral_bed"):
            self.assertIn(expected, self.cases)

    def test_mean_accuracy_does_not_regress(self):
        mean = sum(self.scores.values()) / len(self.scores)
        self.assertGreaterEqual(
            mean, MEAN_IOU_FLOOR,
            f"mean IoU fell to {mean:.3f}; per case: "
            f"{ {k: round(v, 3) for k, v in sorted(self.scores.items())} }",
        )

    def test_no_single_case_collapses(self):
        """
        The failure this catches is the one that was really happening: a
        garment stored as a scrap of the surface it was lying on.
        """
        for case, score in sorted(self.scores.items()):
            if case in self.kept:
                continue  # declining to cut is a correct answer, not a score
            self.assertGreaterEqual(
                score, WORST_CASE_FLOOR,
                f"{case} scored {score:.3f} with engine {self.engines[case]} - "
                f"that is a mangled garment, not a cut-out",
            )

    def test_the_ordinary_floor_and_bed_photos_are_accurate(self):
        for case, floor in EVERYDAY_CASES.items():
            self.assertGreaterEqual(
                self.scores[case], floor,
                f"{case} scored {self.scores[case]:.3f}, below {floor}",
            )

    def test_a_white_garment_on_white_bedding_is_not_mangled(self):
        """
        The case that was broken: IoU 0.003, stored anyway. Either it is
        segmented properly now, or the photo is kept - never a scrap.
        """
        case = "white_tshirt_white_bed"
        self.assertTrue(
            case in self.kept or self.scores[case] >= WORST_CASE_FLOOR,
            f"{case} scored {self.scores[case]:.3f} and was still used",
        )

    # ---------- the checks that make the above possible ----------

    def test_an_implausible_mask_is_rejected(self):
        """A scatter of patches is not a garment, whatever its size."""
        img = Image.open(os.path.join(BENCH_DIR, "bench",
                                      "tshirt_tiled_floor.png")).convert("RGB")
        scatter = np.zeros(np.asarray(img).shape[:2], np.float32)
        step = 11
        scatter[::step, ::step] = 1.0          # 1/121 of the frame, everywhere
        scatter[100:400, 100:400] = (np.random.default_rng(1).random((300, 300)) > 0.6)

        self.assertFalse(self.pipeline.mask_is_plausible(img, scatter))

    def test_a_correct_mask_is_accepted(self):
        img = Image.open(os.path.join(BENCH_DIR, "bench",
                                      "tshirt_tiled_floor.png")).convert("RGB")
        truth = np.asarray(
            Image.open(os.path.join(BENCH_DIR, "bench",
                                    "tshirt_tiled_floor_truth.png"))
        ).astype(np.float32) / 255.0

        self.assertTrue(self.pipeline.mask_is_plausible(img, truth))

    def test_an_empty_or_everything_mask_is_rejected(self):
        img = Image.open(os.path.join(BENCH_DIR, "bench",
                                      "tshirt_on_bed.png")).convert("RGB")
        shape = np.asarray(img).shape[:2]

        self.assertFalse(self.pipeline.mask_is_plausible(img, np.zeros(shape, np.float32)))
        self.assertFalse(self.pipeline.mask_is_plausible(img, np.ones(shape, np.float32)))

    def test_bbox_fill_separates_a_garment_from_a_scatter(self):
        solid = np.zeros((400, 400), np.float32)
        solid[100:300, 120:280] = 1.0
        self.assertGreater(self.pipeline._bbox_fill(solid), 0.9)

        scattered = np.zeros((400, 400), np.float32)
        scattered[100:300:7, 120:280:7] = 1.0
        self.assertLess(self.pipeline._bbox_fill(scattered), self.pipeline.MIN_BBOX_FILL)

    def test_a_processed_photo_keeps_the_garment_and_reports_honestly(self):
        """End to end: the thing the upload route actually calls."""
        path = os.path.join(BENCH_DIR, "bench", "tshirt_tiled_floor.png")
        result = self.pipeline.process_clothing_photo(path)

        self.assertIn("image", result)
        self.assertIn(result["engine"], ("rembg", "opencv-grabcut", "segmentation failed"))
        self.assertIsInstance(result["background_removed"], bool)
        # 3:4 for the wardrobe card, and not blown up beyond the cap.
        width, height = result["image"].size
        self.assertAlmostEqual(width / height, 3 / 4, places=1)
        self.assertLessEqual(max(width, height), self.pipeline.MAX_SIDE)


if __name__ == "__main__":
    unittest.main()
